# Generated by Django 4.0.5 on 2022-07-11 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplates',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdf_templates/'),
            preserve_default=False,
        ),
    ]
