# Generated by Django 4.0.5 on 2022-07-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0008_rename_pdf_source_id_pdftemplatecoordinates_pdf_src_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdftemplatecoordinates',
            name='pdf_src_id',
        ),
    ]
