# Generated by Django 4.0.5 on 2022-07-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0010_pdftemplatecoordinates_pdf_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_source_id', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pdf_process')),
            ],
        ),
        migrations.CreateModel(
            name='PdfProcessImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('process_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_template.pdfprocess')),
            ],
        ),
    ]
