# Generated by Django 4.0.5 on 2022-07-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0013_pdftemplates_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplatecoordinates',
            name='field_type',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftemplatecoordinates',
            name='in_date_format',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftemplatecoordinates',
            name='out_date_format',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
