# Generated by Django 4.0.5 on 2022-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0014_pdftemplatecoordinates_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplatecoordinates',
            name='detail_field',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftemplatecoordinates',
            name='height_diff',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdftemplatecoordinates',
            name='total_rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
