# Generated by Django 4.0.5 on 2022-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0016_remove_pdftemplatecoordinates_detail_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdftemplates',
            name='detail_field',
        ),
        migrations.RemoveField(
            model_name='pdftemplates',
            name='total_rows',
        ),
        migrations.AddField(
            model_name='pdftemplatecoordinates',
            name='detail_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdftemplates',
            name='height_diff',
            field=models.IntegerField(default=0),
        ),
    ]
