# Generated by Django 4.0.5 on 2022-08-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0017_remove_pdftemplates_detail_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplates',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
    ]
