# Generated by Django 4.0.5 on 2022-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_template', '0018_pdftemplates_total_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfprocess',
            name='process_count',
            field=models.IntegerField(default=0),
        ),
    ]
